### ISSUE TITLE
Problem about "Dimension 0 in both shapes must be equal, but are 9 and 3 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [3,3,3,64]."

### ISSUE THREAD

**Issue by TianChenone** [tensorlayer/srgan#113]
Traceback (most recent call last):
  File "main.py", line 355, in <module>
    evaluate()
  File "main.py", line 324, in evaluate
    tl.files.load_and_assign_npz(sess=sess, name=checkpoint_dir+'/g_srgan.npz', network=net_g)
  File "/home/tina/tensorflow_about/SRGAN_Wasserstein-master/tensorlayer/files.py", line 723, in load_and_assign_npz
    assign_params(sess, params, network)
  File "/home/tina/tensorflow_about/SRGAN_Wasserstein-master/tensorlayer/files.py", line 692, in assign_params
    ops.append(network.all_params[idx].assign(param))
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 573, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/tina/anaconda2/envs/tensorflow1.4/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 9 and 3 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [3,3,3,64].

I download the pretrained model g_srgan.npz and vgg19.npy and put them in checkpoint. When run python main.py --mode=evaluate , the error will show up. Please help me with the problem. Thanks!

**Comment by TianChenone** [comment]
Thank you! I probably know the reason. And I still have a question is that if I want to change a little on the structure of the SRGAN exactly on SRGAN_g, I will face following dilemma:
If I run "python main.py" directly without download g_sran.npz.
The command line will show error information like "failed to load checkpoint/g_sran.npz;failed to load checkpoint/g_sran_init.npz..."
But if I put the g_sran.npz(the pre-trained model you supply)in the checkpoint, this error disappears, instead of the error of "ValueError: Dimension 0 in both shapes must be equal, but are 9 and 3 for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [3,3,3,64]." 
I guess it is caused by the different between variables' number of new model and pre-trained model, but how can I solve it? Thank you very much!
I run the project on TF1.4.0 and TL1.8.0.

**Comment by TianChenone** [comment]
Excuse me again, when training the model from the beginning, there will be error "failed to load d_srgan.npz"? But I only have g_srgan.npz, how to solve the problem? I also view other comments but didn't find the way .Thank you.

**Comment by TianChenone** [comment]
I have solved my problem by putting vgg19.npy outside the checkpoint just in SRGAN_Wasserstein-master.  = =
