### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'weights'

### ISSUE THREAD

**Issue by yjlintw** [tensorlayer/srgan#144]
When I train the model with the dataset specified in the readme file. I got the following error
```
Traceback (most recent call last):
  File ".\train.py", line 357, in <module>
    train()
  File ".\train.py", line 102, in train
    grad = tape.gradient(mse_loss, G.weights)
AttributeError: 'Model' object has no attribute 'weights'
```
Any idea how to fix it?

**Comment by yjlintw** [comment]
It seams to work after I change `G.weights` to `G.trainable_weights`

**Comment by PeeJay** [comment]
Same problem here. There are a few instances that need changing.

**Comment by YYangZiXin** [comment]
Same problem

**Comment by rinabell** [comment]
> It seams to work after I change `G.weights` to `G.trainable_weights`

It works perfect for me.

**Comment by LaterBetterThanNever** [comment]
I update the version of tensorlayer > 2.0.0, and it works.
