### ISSUE TITLE
too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by AndrzejBandurski** [tensorlayer/srgan#149]
https://github.com/tensorlayer/srgan/blob/16c2e3f3d478a59675260d7d30389db110d0e0e3/train.py#L113

Traceback (most recent call last):
  File "train.py", line 356, in <module>
  File "train.py", line 113, in train

ValueError: too many values to unpack (expected 2)

**Comment by YonghuiXu** [comment]
Hi,is this problem solved? I also encountered the same situation.

**Comment by Fredy** [comment]
replace
```python
for step, (lr_patchs, hr_patchs) in train_ds: 
```
with 
```python
for step, (lr_patchs, hr_patchs) in enumerate(train_ds): 
```

**Comment by AndrzejBandurski** [comment]
I have corrected this already by myself, thank you very much for conforming !

new Issue though...
line 128: RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes

**Comment by zsdonghao** [comment]
@AndrzejBandurski set `persistent=True`
