### ISSUE TITLE
InvalidArgumentError: Matrix size-incompatible: In[0]: [4,4096], In[1]: [256,1] [Op:MatMul] name: MatMul/

### ISSUE THREAD

**Issue by YonghuiXu** [tensorlayer/srgan#152]
Traceback (most recent call last):

  File "<ipython-input-2-c15e78fc333e>", line 1, in <module>
    runfile('/home/dongwen/Desktop/SRGAN/train.py', wdir='/home/dongwen/Desktop/SRGAN')

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/dongwen/Desktop/SRGAN/train.py", line 292, in <module>
    train()

  File "/home/dongwen/Desktop/SRGAN/train.py", line 148, in train
    logits_fake = D(fake_patchs)

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorlayer/models/core.py", line 296, in __call__
    return self.forward(inputs, **kwargs)

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorlayer/models/core.py", line 339, in forward
    memory[node.name] = node(node_input)

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorlayer/layers/core.py", line 431, in __call__
    outputs = self.layer.forward(inputs, **kwargs)

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorlayer/layers/dense/base_dense.py", line 106, in forward
    z = tf.matmul(inputs, self.W)

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 2580, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)

  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5753, in mat_mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

InvalidArgumentError: Matrix size-incompatible: In[0]: [4,4096], In[1]: [256,1] [Op:MatMul] name: MatMul/

**Comment by zsdonghao** [comment]
the patch size is incorrect, did you crop the image

**Comment by YonghuiXu** [comment]
Yes,I crop the image to 128*128. What I want to do is the input is 128*128,and the output is 128*128,too.I have modified the generator (delete the SunpixelConv2d layers). The output image is 4*128*128*3,but when I input it to discriminator, then I got this error.  




------------------ 原始邮件 ------------------
发件人: "Hao"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 中午11:52
收件人: "tensorlayer/srgan"<srgan@noreply.github.com>;
抄送: "姐妹的海洋"<2259949930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tensorlayer/srgan] InvalidArgumentError: Matrixsize-incompatible: In[0]: [4,4096], In[1]: [256,1] [Op:MatMul] name: MatMul/(#152)




the patch size is incorrect, did you crop the image

**Comment by zsdonghao** [comment]
you need to change the shape of the input layer of the discriminator

**Comment by YonghuiXu** [comment]
> you need to change the shape of the input layer of the discriminator

Thanks. I changed the discriminator wrong.

**Comment by khg2478** [comment]
> > you need to change the shape of the input layer of the discriminator
> 
> Thanks. I changed the discriminator wrong.

Hi. I am having the same issue. Could you share how you revised the code?

**Comment by YonghuiXu** [comment]
> > > you need to change the shape of the input layer of the discriminator
> > 
> > 
> > Thanks. I changed the discriminator wrong.
> 
> Hi. I am having the same issue. Could you share how you revised the code?
Maybe you change the discriminator layers.

**Comment by amanattrish** [comment]
**I am facing same problem! I did not crop any image. Could you tell whats going wrong?**
![problem](https://user-images.githubusercontent.com/53205776/61924153-33233500-af84-11e9-9cbc-92dc97f6cd07.PNG)

Note:
I am using images from  **DIV2K - bicubic downscaling x4 competition** as recommended in README.md

**Comment by amanattrish** [comment]
@zsdonghao @ChrisWu1997  please help

**Comment by ChrisWu1997** [comment]
Can you print the shape of `fake_patchs`? So to check it is a problem with `G` or `D`. The shape of `fake_patchs` is supposed to be (384, 384, 3).

**Comment by ChrisWu1997** [comment]
@amanattrish  Seems that this issue has been fixed. Check here #166.
