### ISSUE TITLE
The process automatically killed before running adversarial learning.

### ISSUE THREAD

**Issue by amanattrish** [tensorlayer/srgan#169]
When I run **python train.py --mode=evaluate** command I get the following error:

**Traceback (most recent call last):
  File "train.py", line 204, in <module>
    evaluate()
  File "train.py", line 172, in evaluate
    G.load_weights(os.path.join(checkpoint_dir, 'g.h5'))
  File "/home/himanshu/BTP_AB/lib/python3.7/site-packages/tensorlayer/models/core.py", line 944, in load_weights
    raise FileNotFoundError("file {} doesn't exist.".format(filepath))
FileNotFoundError: file models/g.h5 doesn't exist.**

It is may be because **The Process** killed after running through initializing learning (line 89 to 105 in train.py) and before adversarial learning (line 106 to 132 in tran.py).

**Comment by zsdonghao** [comment]
this line saves the model https://github.com/tensorlayer/srgan/blob/master/train.py#L142

you need to wait until the training finished before running the evaluation code.

**Comment by amanattrish** [comment]
You took it wrong. I didn't run evaluation code before finishing. The process automatically killed before running adversarial learning. Hence no saving of model!

**Comment by zsdonghao** [comment]
ok, I change the issue title to `The process automatically killed before running adversarial learning.`

Could you give me the error logging of the auto killing?  Thanks.

**Comment by amanattrish** [comment]
I don't have the error log. But as far as I remember the error was not raised by system and anything that happened was after **filling up buffer suffle** and then there was a just a message **Process Killed**.

**Comment by amanattrish** [comment]
@zsdonghao 
This was the log I got:
**2019-07-30 22:19:35.836425: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 24 of 128
2019-07-30 22:19:45.109756: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 44 of 128
2019-07-30 22:19:55.090488: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 72 of 128
2019-07-30 22:20:06.352649: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 96 of 128
2019-07-30 22:20:15.388401: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 108 of 128
2019-07-30 22:20:28.284132: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:111] Filling up shuffle buffer (this may take a while): 126 of 128
2019-07-30 22:20:28.867526: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:162] Shuffle buffer filled.
W0730 22:24:40.417597 140252395230976 deprecation.py:323] From /home/himanshu/BTP_AB/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py:182: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Killed**

Though I have modified the code for minimising RAM, still before the starting of adversarial learning I am running out of RAM. 
My batchsize is 4, buffersize is 2 and my GPU RAM is 6GB.

**Comment by zsdonghao** [comment]
I see, this way could help: use the method in the following link to load images for each batch instead of reading the entire dataset into the RAM at the beginning.

https://github.com/tensorlayer/dcgan/blob/master/data.py#L28

**Comment by amanattrish** [comment]
Memory problem is also there after running evaluation command. Btw, how to test the model (I mean on test_LR images)?

**Comment by amanattrish** [comment]
I was just a problem of memory. I omitted some of the layers from generator and discriminator and it worked.
