### ISSUE TITLE
problems running on windows

### ISSUE THREAD

**Issue by mcDandy** [tensorlayer/srgan#180]
`python train.py`

2019-10-08 20:55:32.978162: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-10-08 20:55:35.246078: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-10-08 20:55:35.333633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Quadro P1000 major: 6 minor: 1 memoryClockRate(GHz): 1.5185
pciBusID: 0000:01:00.0
2019-10-08 20:55:35.341328: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-08 20:55:35.348135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-08 20:55:35.351468: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-10-08 20:55:35.359874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Quadro P1000 major: 6 minor: 1 memoryClockRate(GHz): 1.5185
pciBusID: 0000:01:00.0
2019-10-08 20:55:35.366853: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-10-08 20:55:35.372725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-08 20:55:36.070183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-08 20:55:36.075760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-10-08 20:55:36.079969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-10-08 20:55:36.084090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3005 MB memory) -> physical GPU (device: 0, name: Quadro P1000, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-10-08 20:55:36.279220: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2019-10-08 20:55:37.369250: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    train()
  File "train.py", line 74, in train
    G = get_G((batch_size, 96, 96, 3))
  File "D:\Users\<Username>\Downloads\srgan-master\model.py", line 27, in get_G
    n = BatchNorm(gamma_init=g_init)(n)
NameError: name 'BatchNorm' is not defined

packages which I noticed installing/ needed to install

tensorboard               2.0.0
tensorflow-estimator 2.0.0
tensorflow-gpu          2.0.0
tensorlayer                 2.1.0

Pillow                         6.2.0
google-pasta            0.1.7
Lasagne                       0.1
Markdown                3.1.1

pip  19.2.3
Python 3.7.4

Os: win10
CUDA computing toolkit 10.1 and 10.0
GPU Nvidia qadro p1000
CPU: Intel core I7 8750H

**Comment by mcDandy** [comment]
![2019-10-08 (28)](https://user-images.githubusercontent.com/18588943/66421537-564c7500-ea08-11e9-8562-1f794d1924eb.png)
Had split second to capture this. cmd.exe cannot cd to another disc and there is not option open in command prompt.

**Comment by mcDandy** [comment]
Is it becouse I use custom dataset of png files? (1920x1080)

**Comment by mcDandy** [comment]
i changed only config.TRAIN.hr_img_path to point into dataset

**Comment by leffey** [comment]
i have same question

**Comment by mcDandy** [comment]
Changed line 27 `n = BatchNorm(gamma_init=g_init)(n)` to ` n = BatchNorm2d(gamma_init=g_init)(n)` and updated tensorflow, but different problem arised

python train.py
2019-10-11 13:54:32.192366: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
100% (70151 of 70151) |##########################################################| Elapsed Time: 0:04:15 ETA:  00:00:00Traceback (most recent call last):
  File "train.py", line 202, in <module>
    train()
  File "train.py", line 76, in train
    VGG = tl.models.vgg19(pretrained=True, end_with='pool4', mode='static')
  File "C:\Program Files\Python37\lib\site-packages\tensorlayer\models\vgg.py", line 317, in vgg19
    restore_model(model, layer_type='vgg19')
  File "C:\Program Files\Python37\lib\site-packages\tensorlayer\models\vgg.py", line 169, in restore_model
    npz = np.load(os.path.join('models', model_saved_name[layer_type]), encoding='latin1').item()
  File "C:\Program Files\Python37\lib\site-packages\numpy\lib\npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\numpy\lib\format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by sintaxed** [comment]
Hey I fixed the Batchnorm problem by adding BatchNorm to the imports at the beginning 

from tensorlayer.layers import (Input, Conv2d, BatchNorm2d, Elementwise, SubpixelConv2d, Flatten, Dense)
->
from tensorlayer.layers import (Input, Conv2d, BatchNorm, BatchNorm2d, Elementwise, SubpixelConv2d, Flatten, Dense)

I had the pickle error too, but the only way I could get around it was by running the script in a native Linux environment. I think I had concluded that tensorflow 2.0.0-b1 was not actually available for windows? I know python3.7 is not available for Windows Python, so that could be the problem too.

**Comment by mcDandy** [comment]
I am using tensorfow 2.0.0 and numpy 1.16.5. Will try it.

**Comment by mcDandy** [comment]
fixed and downgraded numpy

the error is strange, the variable was set in scope few lines on top.

after python train.py
2019-10-18 08:50:28.953029: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2                                                                       Traceback (most recent call last):                                                                                        File "train.py", line 202, in <module>                                                                                    train()                                                                                                               File "train.py", line 104, in train                                                                                       tl.vis.save_images(fake_hr_patchs.numpy(), [2, 4], os.path.join(save_dir, 'train_g_init_{}.png'.format(epoch)))     UnboundLocalError: local variable 'fake_hr_patchs' referenced before assignment

**Comment by mcDandy** [comment]
Dataset of 2 images is too small. small fraction of my dataset (75/about 25k) is enouch to run. Ignore the error above is just becouse too smal dataset.

**Comment by mcDandy** [comment]
Should have closed this issue and create new. This is no longer problem of starting, but training/post training it.
