### ISSUE TITLE
UnboundLocalError: local variable 'fake_hr_patchs' referenced before assignment

### ISSUE THREAD

**Issue by sintaxed** [tensorlayer/srgan#183]
```
WARNING:tensorflow:From /home/bill/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:505: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    train()
  File "train.py", line 104, in train
    tl.vis.save_images(fake_hr_patchs.numpy(), [2, 4], os.path.join(save_dir, 'train_g_init_{}.png'.format(epoch)))
UnboundLocalError: local variable 'fake_hr_patchs' referenced before assignment


```
I don't think the warning matters, but I've included it just in-case. I can run the script upto this point where it saves the images, but can't figure out why I get this error. I'm guessing this loop never happens:

```
with tf.GradientTape() as tape:
                fake_hr_patchs = G(lr_patchs)
                mse_loss = tl.cost.mean_squared_error(fake_hr_patchs, hr_patchs, is_mean=True)

```
but I don't know what the actual problem is.

**Comment by sintaxed** [comment]
"Dataset of 2 images is too small. small fraction of my dataset (75/about 25k) is enouch to run. Ignore the error above is just becouse too smal dataset."

from other thread
