### ISSUE TITLE
UnboundLocalError: local variable 'fake_hr_patchs' referenced before assignment

### ISSUE THREAD

**Issue by sherinaly** [tensorlayer/srgan#191]
Hi I am running the code on Colab and i get this error
---------------------------------------------------------------------
2019-10-31 23:37:31.450293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-10-31 23:37:31.452039: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-10-31 23:37:31.452092: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (0bb177063e0a): /proc/driver/nvidia/version does not exist
2019-10-31 23:37:31.452520: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-31 23:37:31.458325: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-10-31 23:37:31.458608: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x17a0bc0 executing computations on platform Host. Devices:
2019-10-31 23:37:31.458639: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
tcmalloc: large alloc 1359847424 bytes == 0x102e5c000 @  0x7f1364bd71e7 0x7f13209177c2 0x7f132442cffa 0x7f13244b3d39 0x7f13244b569d 0x7f13244b7f2b 0x7f13244b85cc 0x7f13244b9ffc 0x7f132201ef59 0x7f132201fa0e 0x7f1321ffc192 0x7f1321ffcbcf 0x7f1322000a5c 0x7f13220026ba 0x7f131f49e485 0x7f131f43577b 0x50a84f 0x50c549 0x5081d5 0x50a020 0x50aa1d 0x50d320 0x5081d5 0x50a020 0x50aa1d 0x50d320 0x5081d5 0x50a020 0x50aa1d 0x50d320 0x5093e5
Traceback (most recent call last):
  File "/content/gdrive/My Drive/srgan-masterTF2/train.py", line 202, in <module>
    train()
  File "/content/gdrive/My Drive/srgan-masterTF2/train.py", line 104, in train
    tl.vis.save_images(fake_hr_patchs.numpy(), [2, 4], os.path.join(save_dir, 'train_g_init_{}.png'.format(epoch)))
UnboundLocalError: local variable 'fake_hr_patchs' referenced before assignment
---------------------------------------------------------------
Anyone knows how to fix this?
Here is the commands i used for setup
!apt-get install python3
!apt-get install python3-pip
!pip3 install tensorlayer
!pip3 install tensorflow-gpu
!pip3 install https://github.com/tensorlayer/tensorlayer/archive/master.zip
!python3 '/content/gdrive/My Drive/srgan-masterTF2/train.py'

Am I missing anything?

**Comment by GINSENKAZE** [comment]
Traceback (most recent call last):
  File "E:/srgan-master/train.py", line 200, in <module>
    
  File "E:/srgan-master/train.py", line 102, in train
    epoch, n_epoch_init, step, n_step_epoch, time.time() - step_time, mse_loss))
UnboundLocalError: local variable 'fake_hr_patchs' referenced before assignment


I am also have this problem.

**Comment by lwh9346** [comment]
I have this problem too.
I finally found out that it's caused by the lack of train data.
The image loader will only load .png images,if you use .jpg or other image formalts you will face this problem.
You can reformalt your data to solve it.
