### ISSUE TITLE
OSError: Failed to interpret file 'models\\vgg19.npy' as a pickle

### ISSUE THREAD

**Issue by meeng251** [tensorlayer/srgan#217]
Hi all, I have an error like this: 

Traceback (most recent call last):
  File "V:\Python 3.6.8\lib\site-packages\numpy\lib\npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 200, in <module>

  File "train.py", line 74, in train
    G = get_G((batch_size, 96, 96, 3))
  File "V:\Python 3.6.8\lib\site-packages\tensorlayer\models\vgg.py", line 319, in vgg19
    restore_model(model, layer_type='vgg19')
  File "V:\Python 3.6.8\lib\site-packages\tensorlayer\models\vgg.py", line 171, in restore_model
    npz = np.load(os.path.join('models', model_saved_name[layer_type]), allow_pickle=True, encoding='latin1').item()
  File "V:\Python 3.6.8\lib\site-packages\numpy\lib\npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))

OSError: Failed to interpret file 'models\\vgg19.npy' as a pickle

I need help with this problem, someone can have me, please?

**Comment by Laicheng0830** [comment]
The vgg19.npy download is incomplete.
you can try manually download,  copy the model to V:\Python 3.6.8\lib\site-packages\tensorlayer\models\models\

download link:https://github.com/tensorlayer/pretrained-models/tree/master/models

**Comment by Laicheng0830** [comment]
Notes .delete incomplete files in the V:\Python 3.6.8\lib\site-packages\tensorlayer\models\models\vgg19.npy

**Comment by husterwang** [comment]
@Laicheng0830  Sorry, I have the same problem and I haven't solved it by downloading again.

**Comment by Laicheng0830** [comment]
@husterwang You can get the model parameters from [here](https://git.openi.org.cn/attachments/503c8a6c-705f-4fb6-ba18-03d72b6a949a?type=0).

**Comment by husterwang** [comment]
Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorlayer/srgan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorlayer/srgan] OSError: Failed to interpret file 'models\\vgg19.npy' as a pickle (#217)





 
@husterwang You can get the model parameters from here.
