### ISSUE TITLE
tensorlayerx.nn.layers.deprecated.NonExistingLayerError: SequentialLayer(layer) --> Sequential(layer)(in)

### ISSUE THREAD

**Issue by wajoud** [tensorlayer/srgan#244]
Using TensorFlow backend.
2022-04-26 18:53:56.612121: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-26 18:53:56.616458: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/home/wajoud/srgan/train.py", line 105, in <module>
    G = SRGAN_g()
  File "/home/wajoud/srgan/srgan.py", line 34, in __init__
    self.residual_block = self.make_layer()
  File "/home/wajoud/srgan/srgan.py", line 46, in make_layer
    return SequentialLayer(layer_list)
  File "/home/wajoud/anaconda3/envs/srgan/lib/python3.9/site-packages/tensorlayerx/nn/layers/deprecated.py", line 451, in SequentialLayer
    raise NonExistingLayerError("SequentialLayer(layer) --> Sequential(layer)(in)" + __log__)
tensorlayerx.nn.layers.deprecated.NonExistingLayerError: SequentialLayer(layer) --> Sequential(layer)(in)
 Hint: 1) downgrade TL from version TensorLayerX to TensorLayer2.x. 2) check the documentation of TF version 2.x and TL version X

facing this issue can someone help me out !! thank you

**Comment by hanjr92** [comment]
Sorry too late to reply you!  I will update my code and fix this bug.  @wajoud

**Comment by hanjr92** [comment]
I have updated codes. Now, you can run this script under TensorLayerX. If you like this project, please support it and star it : ). @wajoud
