### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by 1056602658** [tensorlayer/SRGAN#260]
Traceback (most recent call last):
  File "C:\Users\lzc\Desktop\SRGAN-master\train.py", line 120, in <module>
    G.init_build(tlx.nn.Input(shape=(8, 3, 96, 96)))
  File "D:\anaconda3\Lib\site-packages\tensorlayerx\nn\core\core_tensorflow.py", line 634, in init_build
    self.forward(*inputs, **kwargs)
  File "C:\Users\lzc\Desktop\SRGAN-master\srgan.py", line 71, in forward
    x = self.subpiexlconv1(x)
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\tensorlayerx\nn\core\core_tensorflow.py", line 173, in __call__
    output = self.forward(inputs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\tensorlayerx\nn\layers\convolution\super_resolution.py", line 184, in forward
    outputs = self.depth_to_space(inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\tensorlayerx\backend\ops\tensorflow_backend.py", line 1675, in __call__
    return tf.nn.depth_to_space(input, block_size=self.block_size, data_format=self.data_format)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\tensorflow\python\ops\weak_tensor_ops.py", line 88, in wrapper
    return op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\anaconda3\Lib\site-packages\tensorflow\python\framework\ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node DepthToSpace}} = DepthToSpace[T=DT_FLOAT, block_size=2, data_format="NCHW"]
All kernels registered for op DepthToSpace:
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_QINT8, DT_QUINT8, DT_QINT32, DT_BFLOAT16, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64, DT_FLOAT8_E5M2, DT_FLOAT8_E4M3FN, DT_INT4, DT_UINT4]

**Comment by 1056602658** [comment]
请问有人可以帮帮我吗？

**Comment by Fragtex254** [comment]
Same problem！！！my  CPU is amd R7-6800U and my is nvidia laptop 3050(4g).is it possiblem to train model in this device?
My python version :3.10.14? Maybe I can low down the py version???

**Comment by MrLee12138** [comment]
你好，我也遇到了同样的问题，请问你解决了吗？
