### ISSUE TITLE
I download 32622.zip and only find the g_srgan.npz,but where is d_srgan.npz?

### ISSUE THREAD

**Issue by ratsuki** [tensorlayer/SRGAN#49]

**Comment by jimlynnjulian** [comment]
My most recent crash with TF 1.5.1, TL 1.8 and SRGAN on Windows 10 Pro: 
(I'm using a 2008 Dell laptop. That's why I'm not using the most recent version of TF.)
[TL] [*] Load checkpoint/g_srgan.npz SUCCESS!
[TL] [!] Load checkpoint/d_srgan.npz failed!
Traceback (most recent call last):
  File "main.py", line 309, in <module>
  File "main.py", line 113, in train
    ###========================= LOAD VGG ========================###
NameError: name 'os' is not defined
C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\srgan-master>

Do I need d_srgan?
I think the os error may go away if I move the import statement down the page several lines.
Any suggestions?
I cannot provide the verification on Broadview site, but I found a copy of g_srgan.npz elsewhere.
Still looking for d_srgan.npz.
jimlynnjulian2@yahoo.com
I noticed the model does not do well since no people images were included in the training.
Would retraining be difficult and time consuming for people models?
I want to couple SRGAN with the SRGAN video processor on github.
 
Thank you,
Jim Julian

**Comment by jimlynnjulian** [comment]
Hello,

   How do I remove the referenc to d_srgan.npz? I have been thinking the missing d_srgan.npz was causing the crash. Am I correct in assuming the crash and the missing d_srgan.npz are not related?

   The 'import os' statement is at the top of the file. I moved the statement down several lines from line 4 to line 14 with no effect.

   Thank you.

**Comment by zsdonghao** [comment]
`d_srgan.npz` only effect for training, not inference, it should be fine.

**Comment by yyy13** [comment]
>           Hello,
> How do I remove the referenc to d_srgan.npz? I have been thinking the missing d_srgan.npz was causing the crash. Am I correct in assuming the crash and the missing d_srgan.npz are not related?
> The 'import os' statement is at the top of the file. I moved the statement down several lines from line 4 to line 14 with no effect.
> Thank you.

have you solved the problem :NameError: name 'os' is not defined. I have the same problem but i have improted os.  Don't know why.

**Comment by linhdvu14** [comment]
@zsdonghao I'd like to retrain. Where do I find `d_srgan.npz`? Thanks!

**Comment by amrbenattia** [comment]
Hello @zsdonghao ,
Is there a way to Tensorboard the losses with epochs.
How to calculate the psnr and ssim ?

Thanks

**Comment by rdevi-pz** [comment]
@zsdonghao  I am using release 1.2.1 that supports TF 1.4
Even though the main.py has import time included, the following issue occurs. Could you please suggest a solution.

NameError: name 'time' is not defined

**Comment by Chanwb** [comment]
> @zsdonghao 我正在使用支持TF 1.4的1.2.1版，
> 即使main.py包含了导入时间，也会出现以下问题。您能否提出解决方案。
> 
> NameError：名称“时间”未定义
Hava you solved this problem guy?

**Comment by Chanwb** [comment]
> @zsdonghao I am using release 1.2.1 that supports TF 1.4
> Even though the main.py has import time included, the following issue occurs. Could you please suggest a solution.
> 
> NameError: name 'time' is not defined

Have you solved this problem?

**Comment by Chanwb** [comment]
> you don't need d_srgan for inferencing.
> 
> for the `os`, pls `import os`

I have the same problem, but i have imported os module, do you have any other solution?
