### ISSUE TITLE
issue when training -- wrong image name

### ISSUE THREAD

**Issue by zhanglijun95** [tensorlayer/SRGAN#52]
Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/amiao/Documents/SR_raw_material/SRGAN-master/tensorlayer/prepro.py", line 89, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/home/amiao/Documents/SR_raw_material/SRGAN-master/utils.py", line 14, in get_imgs_fn
    return scipy.misc.imread(path + file_name, mode='RGB')
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2295, in open
    % (filename if filename else fp))
IOError: cannot identify image file '/home/amiao/Documents/SR_raw_material/SRGAN-master/DIV2K_train_HR/._0393.png'

When I run the main.py, the terminal show me the above issue about false image names.

**Comment by zsdonghao** [comment]
Hi, why there is a `._0393.png` ? I think it will run when after deleting it.

**Comment by MurtazaNajaf** [comment]
CAN I  USE LOW RESOULTION  IMAGE TO  ENHANCE IT WITHOUT MANIPULATING THE CODE

**Comment by MurtazaNajaf** [comment]
I AM STILL FACING PROBLEM  HOW TO  CONFIGURE THE PRETRAINED DATA SET
