### ISSUE TITLE
issues when read imgs and finally it shows killed

### ISSUE THREAD

**Issue by Jean332** [tensorlayer/srgan#60]
Hi,thank you for sharing this project! I'm excited and I wanna train it at once.When I reading the imgs,most of the imgs readed normally,but some imgs have problem like this:
……
read 384 from NTIRE_2017/DIV2K_train_HR/
read 416 from NTIRE_2017/DIV2K_train_HR/
read 448 from NTIRE_2017/DIV2K_train_HR/
Exception in thread threading_and_return:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/srgan/tensorlayer/prepro.py", line 99, in apply_fn
    results[i] = fn(data, **kwargs)
  File "/content/drive/srgan/utils.py", line 14, in get_imgs_fn
    return scipy.misc.imread(path + file_name, mode='RGB')
  File "/usr/local/lib/python3.6/dist-packages/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2319, in open
    prefix = fp.read(16)
OSError: [Errno 5] Input/output error

Could you tell me what's the matter?How can I solve the problem?

And after the read step and showed the model's structures,it occured another issues like this:
……
  got  32: SRGAN_d/ho/dense/W:0   (18432, 1)
  got  33: SRGAN_d/ho/dense/b:0   (1,)
[!] Load checkpoint/g_srgan.npz failed!
[!] Load checkpoint/g_srgan_init.npz failed!
[!] Load checkpoint/d_srgan.npz failed!
  Loading conv1_1: (3, 3, 3, 64), (64,)
  Loading conv1_2: (3, 3, 64, 64), (64,)
  Loading conv2_1: (3, 3, 64, 128), (128,)
  Loading conv2_2: (3, 3, 128, 128), (128,)
  Loading conv3_1: (3, 3, 128, 256), (256,)
  Loading conv3_2: (3, 3, 256, 256), (256,)
  Loading conv3_3: (3, 3, 256, 256), (256,)
  Loading conv3_4: (3, 3, 256, 256), (256,)
  Loading conv4_1: (3, 3, 256, 512), (512,)
  Loading conv4_2: (3, 3, 512, 512), (512,)
  Loading conv4_3: (3, 3, 512, 512), (512,)
  Loading conv4_4: (3, 3, 512, 512), (512,)
  Loading conv5_1: (3, 3, 512, 512), (512,)
  Loading conv5_2: (3, 3, 512, 512), (512,)
  Loading conv5_3: (3, 3, 512, 512), (512,)
  Loading conv5_4: (3, 3, 512, 512), (512,)
  Loading fc6: (25088, 4096), (4096,)
  Loading fc7: (4096, 4096), (4096,)
  Loading fc8: (4096, 1000), (1000,)
Killed
Why it's killed?  I'm so confused.Hoping for hearing from you,thank you very much~

**Comment by Jean332** [comment]
Then I change to use Python 2.7,Tensorflow 1.2,tensorlayer-1.7.4, but it didn't help.
Can someone tell me what's the matter?Thank you very much!

**Comment by Jean332** [comment]
I solved it.Maybe it's because I use the google drive,it's somewhat instable,so I shrinked the number of "n_threads" to 8,it's work! Now it's training,haha~
And I wanna know how "n_threads" impact the effect?

**Comment by wagamamaz** [comment]
memory is not enough

**Comment by NadineMM** [comment]
I have the same problem. Where do you change the number of n_threads
