### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by InderpreetSinghChhabra01** [tensorlayer/srgan#62]
Traceback (most recent call last):
File "main.py", line 316, in 
train()
File "main.py", line 141, in train
print('sample HR sub-image:',sample_imgs_384.shape, sample_imgs_384.min(), sample_imgs_384.max())
File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 29, in _amin
return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by JermySing** [comment]
I encounter the same trouble. Have you solved this? Can you give me some suggestion?

**Comment by OValery16** [comment]
same error
