### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by Wisgon** [tensorlayer/srgan#68]
when I run : python main.py --mode=evaluate 
I got this:
Traceback (most recent call last):
  File "main.py", line 310, in <module>
    evaluate()
  File "main.py", line 275, in evaluate
    net_g = SRGAN_g(t_image, is_train=False, reuse=False)
  File "/home/jhd/face_recognition/softwares/srgan_tensor/model.py", line 35, in SRGAN_g
    nn = ElementwiseLayer([n, nn], tf.add, 'b_residual_add/%s' % i)
  File "/home/jhd/face_recognition/anaconda3/envs/compare/lib/python2.7/site-packages/tensorlayer/layers/merge.py", line 120, in __init__
    self.outputs = act(self.outputs)
TypeError: 'str' object is not callable

so I change  "nn=ElementwiseLayer([n, nn], tf.add, 'b_residual_add/%s' % i)"  
TO
"nn=ElementwiseLayer([n, nn], tf.add,  name = 'b_residual_add/%s' % i)"  

Then the problem solve.

**Comment by arisliang** [comment]
Create a PR might be an idea.
