### ISSUE TITLE
Value error in train: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by njzhaixiang** [tensorlayer/srgan#92]
Traceback (most recent call last):
  File "main.py", line 310, in <module>
    train()
  File "main.py", line 135, in train
    print('sample HR sub-image:', sample_imgs_384.shape, sample_imgs_384.min(), sample_imgs_384.max())
  File "/home/chai/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by Nodice** [comment]
Getting the same Error.

Using Tensorflow 1.9

As with most issues with tensorflow projects I suspect it is an issue with the tensorflow version as the project states that it is built for 1.4.

Would be nice if someone could shed light on this as there are multiple issues opened for this error.

**Comment by Nodice** [comment]
So this issue is just Programming 101, always check your assumptions. Turns out my images where not in the correct locations. Unzipping the sample images causes a sub folder to be created. Make sure the images are not in a double folder and exactly match what is in the config.py

**Comment by MurtazaNajaf** [comment]
i  am getting this error could you please suggest me what to  do 

Exception in thread threading_and_return:
Traceback (most recent call last):
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\tensorlayer\prepro.py", line 184, in apply_fn
    results[i] = fn(data, **kwargs)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\tensorlayer\visualize.py", line 52, in read_image
    return imageio.imread(os.path.join(path, image))
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\imageio\core\functions.py", line 206, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\imageio\core\functions.py", line 129, in get_reader
    return format.get_reader(request)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\imageio\core\format.py", line 168, in get_reader
    return self.Reader(self, request)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\imageio\core\format.py", line 217, in __init__
    self._open(**self.request.kwargs.copy())
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\imageio\plugins\pillow.py", line 277, in _open
    pilmode=pilmode, as_gray=as_gray)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\imageio\plugins\pillow.py", line 125, in _open
    pil_try_read(self._im)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\imageio\plugins\pillow.py", line 491, in pil_try_read
    im.getdata()[0]
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\PIL\Image.py", line 1220, in getdata
    self.load()
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 190, in load
    self.load_prepare()
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\PIL\PngImagePlugin.py", line 609, in load_prepare
    ImageFile.ImageFile.load_prepare(self)
  File "C:\Users\MurtazaNajaf\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 258, in load_prepare
    self.im = Image.core.new(self.mode, self.size)

**Comment by Nodice** [comment]
Looks like an Issue with your Anaconda3. I don't have experience with Tensorflow inside of Anaconda.

Validate first that Tensorflow, or Tensorflow-GPU is running fine by following the google tensorflow install instructions.

If that is working, first try to train the project using the images mentioned in the project. There are links to download them. You have to make sure the folder structure matches exactly.

If you are training against your own images, I found that the project can only handle 24bit images in PNG format. It cannot handle 32bit and messes up. Your error could be related to that.

**Comment by TianChenone** [comment]
When you train the model from the beginning, is there an error like "failed to load d_srgan.npz"? If there is,
how to resolve? Thank you.
